{ pkgs, config, ... }:
let
  wallDir = "${config.home.homeDirectory}/Pictures/Wallpapers";
  cacheDir = "${config.home.homeDirectory}/.cache/wall-thumbs";
  rofiTheme = "${config.home.homeDirectory}/.config/rofi/WallSelect.rasi";

  # Import the brain script
  paletteGenScript = builtins.readFile ./palette-gen.sh;
in
{
  home.packages = [
    pkgs.libnotify
    pkgs.imagemagick
    pkgs.findutils
    pkgs.coreutils
    pkgs.pastel
    pkgs.jq
    pkgs.gnused

    # 1. The Palette Generator (Exposed to PATH)
    (pkgs.writeShellScriptBin "palette-gen" paletteGenScript)

    # 1.5 The CLI Helper (Quick Preview)
    (pkgs.writeShellScriptBin "palette" ''
      if [ -z "$1" ]; then
        echo "Usage: palette <filename_or_path>"
        echo "Default Dir: ~/Pictures/Wallpapers/"
        exit 1
      fi

      INPUT="$1"
      WALL_DIR="$HOME/Pictures/Wallpapers"

      # Logic: Check absolute path first, then check Wallpaper dir
      if [ -f "$INPUT" ]; then
          TARGET="$INPUT"
      elif [ -f "$WALL_DIR/$INPUT" ]; then
          TARGET="$WALL_DIR/$INPUT"
      else
          echo "❌ Image not found."
          echo "Checked: $INPUT"
          echo "Checked: $WALL_DIR/$INPUT"
          exit 1
      fi

      # Call the generator in preview mode
      palette-gen "$TARGET" --preview
    '')

    # 2. The Engine (Applies the colors)
    (pkgs.writeShellScriptBin "theme-engine" ''
      set -e
      IMG="$1"
      echo "[Engine] Processing: $IMG"

      # --- CALL THE BRAIN ---
      # This sources the variables: BG, FG, SEM_RED, UI_PRIM, etc.
      eval "$(palette-gen "$IMG")"

      # --- APPLY TO CONFIGS ---

      # 1. NIRI (UI Colors)
      cat <<EOF > "$HOME/.config/niri/colors.kdl"
      // Generated by theme-engine
      window-rule {
          border {
              active-color "$UI_PRIM"
              inactive-color "$UI_SEC"
              width 2
          }
      }
      EOF

      # 2. ROFI (UI Colors)
      cat <<EOF > "$HOME/.config/rofi/colors.rasi"
      * {
          background:     $BG;
          background-alt: $UI_SEC;
          foreground:     $FG;
          selected:       $UI_PRIM;
          text-selected:  $BG;
          active:         $SYN_KEY;
          urgent:         $SEM_RED;
      }
      EOF

      # 3. VESKTOP (UI + Semantics)
            # We import Midnight Discord to handle the heavy lifting
            cat <<EOF > "$HOME/.config/vesktop/themes/lis.theme.css"
            /** Generated by theme-engine **/
            @import url("https://refact0r.github.io/midnight-discord/build/midnight.css");
            :root {
                --background-primary: $BG;
                --background-secondary: $UI_SEC;
                --background-tertiary: $BG;
                --text-normal: $FG;
                --text-muted: $FG_DIM;
                --header-primary: $SYN_KEY;
                --interactive-active: $UI_PRIM;
                --interactive-normal: $FG;
                --brand-experiment: $UI_PRIM; /* Main Accent */
            }
            EOF

      # 4. GTK
      cat <<EOF > "$HOME/.config/gtk-3.0/gtk.css"
      @define-color theme_bg_color $BG;
      @define-color theme_fg_color $FG;
      @define-color theme_selected_bg_color $UI_PRIM;
      @define-color theme_selected_fg_color $BG;
      window { background: $BG; color: $FG; }
      view { background: $UI_SEC; color: $FG; }
      headerbar { background: $BG; }
      EOF
      cp "$HOME/.config/gtk-3.0/gtk.css" "$HOME/.config/gtk-4.0/gtk.css"

      # 5. KITTY
      cat <<EOF > "$HOME/.cache/wal/colors-kitty.conf"
      foreground $FG
      background $BG
      cursor $UI_PRIM
      color0 $BG
      color8 $UI_SEC
      color1 $SEM_RED
      color9 $SEM_RED
      color2 $SEM_GREEN
      color10 $SEM_GREEN
      color3 $SEM_YELLOW
      color11 $SEM_YELLOW
      color4 $SEM_BLUE
      color12 $SEM_BLUE
      color5 $SYN_KEY
      color13 $SYN_KEY
      color6 $SYN_FUN
      color14 $SYN_FUN
      color7 $FG
      color15 $FG
      EOF

      # 6. ZED EDITOR (The Big Fix)
      TEMPLATE="$HOME/.config/wal/templates/zed.template"
      OUTPUT="$HOME/.config/zed/themes/LisTheme.json" # Kept filename for compatibility

      if [ -f "$TEMPLATE" ]; then
        cp "$TEMPLATE" "$OUTPUT"
        replace() { sed -i "s|{$1}|$2|g" "$OUTPUT"; }

        # Base
        replace "bg" "$BG"
        replace "fg" "$FG"
        replace "fg_dim" "$FG_DIM"

        # UI
        replace "ui_prim" "$UI_PRIM"
        replace "ui_sec" "$UI_SEC"

        # Semantics (Strict)
        replace "sem_red" "$SEM_RED"
        replace "sem_green" "$SEM_GREEN"
        replace "sem_yellow" "$SEM_YELLOW"
        replace "sem_blue" "$SEM_BLUE"

        # Thematics (Vibrant)
        replace "syn_key" "$SYN_KEY"
        replace "syn_fun" "$SYN_FUN"
        replace "syn_str" "$SYN_STR"
        replace "syn_acc" "$SYN_ACC"
      fi

      echo "[Engine] Configuration Complete."
    '')

    # 3. The Manager (Triggers updates)
    (pkgs.writeShellScriptBin "theme-manager" ''
      set -e
      IMG="$1"
      if [ -z "$IMG" ]; then echo "Usage: theme-manager <path>"; exit 1; fi

      if ! pgrep -x swww-daemon > /dev/null; then swww-daemon & sleep 0.5; fi
      swww img "$IMG" --transition-type grow --transition-pos 0.5,0.5 --transition-fps 60 --transition-duration 2

      ln -sf "$IMG" "$HOME/.cache/current_wallpaper.jpg"
      ${pkgs.imagemagick}/bin/magick "$IMG" -resize ^640x1080 -gravity center -extent 640x1080 "$HOME/.cache/rofi-launcher.jpg" || true

      # Call the Engine
      theme-engine "$IMG"

      # Reload Apps
      systemctl --user start niri-config-assembler.service
      niri msg action load-config-file
      if pgrep -x kitty > /dev/null; then
          kitty @ --to=unix:@mykitty set-colors -a -c ~/.cache/wal/colors-kitty.conf || true
      fi

      notify-send "Theme Active" "$(basename "$IMG")" -i "$IMG"
    '')

    # 4. Wall Select (Rofi Menu)
    (pkgs.writeShellScriptBin "wall-select" ''
      THUMB_WIDTH=415
      THUMB_HEIGHT=550
      export PATH=${pkgs.imagemagick}/bin:${pkgs.coreutils}/bin:${pkgs.rofi}/bin:${pkgs.findutils}/bin:${pkgs.libnotify}/bin:$PATH
      export CACHE_DIR="${cacheDir}"
      mkdir -p "$CACHE_DIR"

      if [ ! -d "${wallDir}" ]; then
        notify-send "Error" "Wallpaper dir missing: ${wallDir}" -u critical
        exit 1
      fi

      # Generate Thumbs
      find -L "${wallDir}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | \
      xargs -0 -P $(nproc) -I {} sh -c '
        img="{}"
        filename=$(basename "$img")
        cache="$CACHE_DIR/$filename"
        if [ ! -f "$cache" ]; then
          magick "$img" -thumbnail "415x550^" -gravity center -extent 415x550 "$cache" 2>/dev/null || true
        fi
      '

      # Select
      SELECTED=$( \
        find -L "${wallDir}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | \
        xargs -0 basename -a | \
        sort | \
        while IFS= read -r filename; do
            printf "%s\0icon\x1f%s/%s\n" "$filename" "$CACHE_DIR" "$filename"
        done | \
        ${pkgs.rofi}/bin/rofi -dmenu -theme "${rofiTheme}" -p "Select Wallpaper" -show-icons \
      )

      if [ -n "$SELECTED" ]; then
        theme-manager "${wallDir}/$SELECTED"
      fi
    '')
  ];

  # Ensure the Zed template exists
  xdg.configFile."wal/templates/zed.template".source = ../templates/zed.template;
}
