{ ... }:
let
  variables = import ../../hosts/variables.nix;
  defaultShell = variables.defaultShell or "zsh";
in
{
  # Keep this to hook Starship into Zsh/Bash automatically
  programs.starship.enable = defaultShell != "fish";

  # Define the Template
  xdg.configFile."wal/templates/starship.toml".text = ''
    # Generated by NixOS (Layout) - Filled by Theme-Engine (Colors)
    add_newline = false

    [directory]
    style = "bold {syn_key}"
    format = "[$path]($style)[$read_only]($read_only_style) "

    [character]
    success_symbol = "[❯](bold {sem_green})"
    error_symbol = "[❯](bold {sem_red})"
    vimcmd_symbol = "[❮]({sem_blue})"

    [nix_shell]
    format = "[$symbol]($style) "
    symbol = "🐚"
    style = "{ui_prim}"

    [git_branch]
    symbol = " "
    # We use UI_SEC for the bubble background (was background-alt)
    format = "[]({ui_sec})on [$symbol$branch]($style)[]({ui_sec}) "
    style = "fg:{syn_fun} bg:{ui_sec}"

    [git_status]
    style = "{sem_yellow}"
    stashed = "≡"

    [git_state]
    style = "{fg_dim}"
    format = "([$state( $progress_current/$progress_total)]($style)) "
  '';
}
