{ lib, ... }:
let
  # Your layout variables can stay here or be imported!
  symbol_nix = " ";
  symbol_git = " ";
in
{
  # We install the package in packages.nix, so we don't need programs.starship.enable = true
  # But we do need to generate the template.

  xdg.configFile."wal/templates/starship.toml".text = ''
    # Generated by NixOS (Layout) - Filled by Theme-Engine (Colors)
    add_newline = false

    [directory]
    style = "bold {syn_key}"
    format = "[$path]($style)[$read_only]($read_only_style) "

    [character]
    success_symbol = "[❯](bold {sem_green})"
    error_symbol = "[❯](bold {sem_red})"
    vimcmd_symbol = "[❮]({sem_blue})"

    [nix_shell]
    symbol = "${symbol_nix}"
    style = "{ui_prim}"
    format = "[$symbol]($style) "

    [git_branch]
    symbol = "${symbol_git}"
    style = "bold {syn_fun}"

    [git_status]
    style = "{sem_yellow}"
    stashed = "≡"

    [git_state]
    style = "{fg_dim}"
  '';
}
