{ pkgs, config, ... }:
let
  wallDir = "${config.home.homeDirectory}/Pictures/Wallpapers";
  cacheDir = "${config.home.homeDirectory}/.cache/wall-thumbs";
  rofiTheme = "${config.home.homeDirectory}/.config/rofi/WallSelect.rasi";
in
{
  home.packages = [
    pkgs.libnotify
    pkgs.imagemagick
    pkgs.findutils
    pkgs.coreutils
    pkgs.pastel
    pkgs.jq
    pkgs.gnused

    # 1. THE UNIFIED ENGINE
    (pkgs.writeShellScriptBin "theme-engine" ''
      set -e
      IMG="$1"
      echo "[Engine] Processing: $IMG"

      # --- 1. EXTRACTION ---
      set +e
      RAW_HEX=$(${pkgs.imagemagick}/bin/magick "$IMG" -scale 1x1! -depth 8 -format "%[hex:u]" info: | cut -c1-6)
      set -e
      if [ -z "$RAW_HEX" ]; then ANCHOR="#2E3440"; else ANCHOR="#$RAW_HEX"; fi

      # --- 2. CALCULATE PALETTE (Split-Complementary) ---

      # UI Base
      BG=$(pastel color "$ANCHOR" | pastel set hsl-saturation 0.15 | pastel set hsl-lightness 0.08 | pastel format hex)
      BG_LIGHT=$(pastel color "$BG" | pastel lighten 0.1 | pastel format hex) # Lighter surface
      FG=$(pastel color "$ANCHOR" | pastel set hsl-saturation 0.10 | pastel set hsl-lightness 0.90 | pastel format hex)
      FG_DIM=$(pastel color "$FG" | pastel darken 0.3 | pastel format hex)

      # Syntax / Accents
      # Keywords (Main Hue)
      C_MAIN=$(pastel color "$ANCHOR" | pastel set hsl-saturation 0.85 | pastel set hsl-lightness 0.65 | pastel format hex)
      # Functions (+30)
      C_SEC=$(pastel color "$ANCHOR" | pastel rotate 30 | pastel set hsl-saturation 0.85 | pastel set hsl-lightness 0.65 | pastel format hex)
      # Strings (-30)
      C_TER=$(pastel color "$ANCHOR" | pastel rotate -- -30 | pastel set hsl-saturation 0.85 | pastel set hsl-lightness 0.65 | pastel format hex)
      # Accent/Cursor (Split-Comp +150)
      C_ACC=$(pastel color "$ANCHOR" | pastel rotate 150 | pastel set hsl-saturation 0.75 | pastel set hsl-lightness 0.70 | pastel format hex)

      ERROR="#ff5555"

      # --- 3. GENERATE CONFIGS ---

      # A. NIRI (Borders)
      cat <<EOF > "$HOME/.config/niri/colors.kdl"
      // Generated by theme-engine
      window-rule {
          border {
              active-color "$C_ACC"
              inactive-color "$BG_LIGHT"
              width 2
          }
      }
      EOF

      # B. ROFI (Launcher Colors)
      cat <<EOF > "$HOME/.config/rofi/colors.rasi"
      * {
          background:     $BG;
          background-alt: $BG_LIGHT;
          foreground:     $FG;
          selected:       $C_ACC;
          text-selected:  $BG;
          active:         $C_MAIN;
          urgent:         $ERROR;
      }
      EOF

      # C. DISCORD (Vesktop CSS)
      cat <<EOF > "$HOME/.config/vesktop/themes/lis.theme.css"
      /** Generated by theme-engine **/
      :root {
          --background-primary: $BG;
          --background-secondary: $BG_LIGHT;
          --background-tertiary: $BG;
          --text-normal: $FG;
          --text-muted: $FG_DIM;
          --header-primary: $C_MAIN;
          --interactive-active: $C_ACC;
          --interactive-normal: $FG;
          --interactive-hover: $C_ACC;
          --brand-experiment: $C_ACC; /* Accent Color */
      }
      EOF

      # D. GTK (CSS)
      cat <<EOF > "$HOME/.config/gtk-3.0/gtk.css"
      @define-color theme_bg_color $BG;
      @define-color theme_fg_color $FG;
      @define-color theme_selected_bg_color $C_ACC;
      @define-color theme_selected_fg_color $BG;
      window { background: $BG; color: $FG; }
      view { background: $BG_LIGHT; color: $FG; }
      headerbar { background: $BG; }
      EOF
      cp "$HOME/.config/gtk-3.0/gtk.css" "$HOME/.config/gtk-4.0/gtk.css"

      # E. KITTY
      cat <<EOF > "$HOME/.cache/wal/colors-kitty.conf"
      foreground $FG
      background $BG
      cursor $C_ACC
      color0 $BG
      color8 $BG_LIGHT
      color1 $ERROR
      color9 $ERROR
      color2 $C_TER
      color10 $C_TER
      color3 $C_MAIN
      color11 $C_MAIN
      color4 $C_SEC
      color12 $C_SEC
      color5 $C_ACC
      color13 $C_ACC
      color6 $C_SEC
      color14 $C_SEC
      color7 $FG
      color15 $FG
      EOF

      # F. ZED
      TEMPLATE="$HOME/.config/wal/templates/zed.template"
      OUTPUT="$HOME/.config/zed/themes/pywal.json"
      if [ -f "$TEMPLATE" ]; then
        cp "$TEMPLATE" "$OUTPUT"
        replace() { sed -i "s|{$1}|$2|g" "$OUTPUT"; }

        replace "background" "$BG"
        replace "foreground" "$FG"
        replace "color0" "$BG_LIGHT" # Lightened BG for active lines
        replace "color1" "$ERROR"

        replace "color2" "$C_TER"   # Strings
        replace "color3" "$C_MAIN"  # Keywords
        replace "color4" "$C_SEC"   # Functions
        replace "color5" "$C_ACC"   # Accent

        # Fill rests
        replace "color6" "$C_TER"
        replace "color7" "$FG"
        replace "color8" "$FG_DIM"
        replace "color9" "$ERROR"
        replace "color10" "$C_TER"
        replace "color11" "$C_MAIN"
        replace "color12" "$C_SEC"
        replace "color13" "$C_ACC"
        replace "color14" "$C_TER"
        replace "color15" "$FG"
      fi

      echo "[Engine] Configuration Complete."
    '')

    # 2. THEME MANAGER (Orchestrator)
    (pkgs.writeShellScriptBin "theme-manager" ''
      set -e
      IMG="$1"
      if [ -z "$IMG" ]; then echo "Usage: theme-manager <path>"; exit 1; fi

      # 1. Wallpaper
      if ! pgrep -x swww-daemon > /dev/null; then swww-daemon & sleep 0.5; fi
      swww img "$IMG" --transition-type grow --transition-pos 0.5,0.5 --transition-fps 60 --transition-duration 2

      # 2. Cache
      ln -sf "$IMG" "$HOME/.cache/current_wallpaper.jpg"
      ${pkgs.imagemagick}/bin/magick "$IMG" -resize ^640x1080 -gravity center -extent 640x1080 "$HOME/.cache/rofi-launcher.jpg" || true

      # 3. RUN THE ENGINE
      theme-engine "$IMG"

      # 4. RELOAD
      systemctl --user start niri-config-assembler.service
      niri msg action load-config-file

      if pgrep -x kitty > /dev/null; then
          kitty @ --to=unix:@mykitty set-colors -a -c ~/.cache/wal/colors-kitty.conf || true
      fi

      notify-send "Theme Active" "$(basename "$IMG")" -i "$IMG"
    '')

    # 3. WALL SELECT
    (pkgs.writeShellScriptBin "wall-select" ''
      THUMB_WIDTH=415
      THUMB_HEIGHT=550
      GEO="415x550"

      export PATH=${pkgs.imagemagick}/bin:${pkgs.coreutils}/bin:${pkgs.rofi}/bin:${pkgs.findutils}/bin:${pkgs.libnotify}/bin:$PATH
      export CACHE_DIR="${cacheDir}"
      mkdir -p "$CACHE_DIR"

      if [ ! -d "${wallDir}" ]; then
        notify-send "Error" "Wallpaper dir missing: ${wallDir}" -u critical
        exit 1
      fi

      find -L "${wallDir}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | \
      xargs -0 -P $(nproc) -I {} sh -c '
        img="{}"
        filename=$(basename "$img")
        cache="$CACHE_DIR/$filename"
        if [ ! -f "$cache" ]; then
          magick "$img" -thumbnail "415x550^" -gravity center -extent 415x550 "$cache" 2>/dev/null || true
        fi
      '

      SELECTED=$( \
        find -L "${wallDir}" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) -print0 | \
        xargs -0 basename -a | \
        sort | \
        while IFS= read -r filename; do
            printf "%s\0icon\x1f%s/%s\n" "$filename" "$CACHE_DIR" "$filename"
        done | \
        ${pkgs.rofi}/bin/rofi -dmenu -theme "${rofiTheme}" -p "Select Wallpaper" -show-icons \
      )

      if [ -n "$SELECTED" ]; then
        theme-manager "${wallDir}/$SELECTED"
      fi
    '')
  ];
}
